//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Media_Distro.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Movie_Media_Location {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Movie_Media_Location"]));
            }
            set {
                this["Movie_Media_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Music_Media_Location {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Music_Media_Location"]));
            }
            set {
                this["Music_Media_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Series_Media_Location {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Series_Media_Location"]));
            }
            set {
                this["Series_Media_Location"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 50, 95")]
        public global::System.Drawing.Color Default_Theme_Preference {
            get {
                return ((global::System.Drawing.Color)(this["Default_Theme_Preference"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 140, 200")]
        public global::System.Drawing.Color Default_Theme_TitleBar {
            get {
                return ((global::System.Drawing.Color)(this["Default_Theme_TitleBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 105, 175")]
        public global::System.Drawing.Color Default_Theme_SearchBar {
            get {
                return ((global::System.Drawing.Color)(this["Default_Theme_SearchBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("235, 245, 250")]
        public global::System.Drawing.Color Default_Theme_WorkPlace {
            get {
                return ((global::System.Drawing.Color)(this["Default_Theme_WorkPlace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Twilight_Theme_WorkPlace {
            get {
                return ((global::System.Drawing.Color)(this["Twilight_Theme_WorkPlace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Meadow_Theme_Preference {
            get {
                return ((global::System.Drawing.Color)(this["Meadow_Theme_Preference"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Meadow_Theme_TitleBar {
            get {
                return ((global::System.Drawing.Color)(this["Meadow_Theme_TitleBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Meadow_Theme_SearchBar {
            get {
                return ((global::System.Drawing.Color)(this["Meadow_Theme_SearchBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Meadow_Theme_WorkPlace {
            get {
                return ((global::System.Drawing.Color)(this["Meadow_Theme_WorkPlace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Fire_Theme_Preference {
            get {
                return ((global::System.Drawing.Color)(this["Fire_Theme_Preference"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Fire_Theme_TitleBar {
            get {
                return ((global::System.Drawing.Color)(this["Fire_Theme_TitleBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Fire_Theme_SearchBar {
            get {
                return ((global::System.Drawing.Color)(this["Fire_Theme_SearchBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Fire_Theme_WorkPlace {
            get {
                return ((global::System.Drawing.Color)(this["Fire_Theme_WorkPlace"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Dark_Theme_Preference {
            get {
                return ((global::System.Drawing.Color)(this["Dark_Theme_Preference"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Dark_Theme_TitleBar {
            get {
                return ((global::System.Drawing.Color)(this["Dark_Theme_TitleBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Dark_Theme_SearchBar {
            get {
                return ((global::System.Drawing.Color)(this["Dark_Theme_SearchBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Dark_Theme_WorkPlace {
            get {
                return ((global::System.Drawing.Color)(this["Dark_Theme_WorkPlace"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 50, 95")]
        public global::System.Drawing.Color Active_Theme_Preference {
            get {
                return ((global::System.Drawing.Color)(this["Active_Theme_Preference"]));
            }
            set {
                this["Active_Theme_Preference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60, 140, 200")]
        public global::System.Drawing.Color Active_Theme_TitleBar {
            get {
                return ((global::System.Drawing.Color)(this["Active_Theme_TitleBar"]));
            }
            set {
                this["Active_Theme_TitleBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 105, 175")]
        public global::System.Drawing.Color Active_Theme_SearchBar {
            get {
                return ((global::System.Drawing.Color)(this["Active_Theme_SearchBar"]));
            }
            set {
                this["Active_Theme_SearchBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("235, 245, 250")]
        public global::System.Drawing.Color Active_Theme_WorkPlace {
            get {
                return ((global::System.Drawing.Color)(this["Active_Theme_WorkPlace"]));
            }
            set {
                this["Active_Theme_WorkPlace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 110, 175")]
        public global::System.Drawing.Color Active_Theme_Selected {
            get {
                return ((global::System.Drawing.Color)(this["Active_Theme_Selected"]));
            }
            set {
                this["Active_Theme_Selected"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 110, 175")]
        public global::System.Drawing.Color Default_Theme_Selected {
            get {
                return ((global::System.Drawing.Color)(this["Default_Theme_Selected"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25, 125, 100")]
        public global::System.Drawing.Color Meadow_Theme_Selected {
            get {
                return ((global::System.Drawing.Color)(this["Meadow_Theme_Selected"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 30, 55")]
        public global::System.Drawing.Color Fire_Theme_Selected {
            get {
                return ((global::System.Drawing.Color)(this["Fire_Theme_Selected"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 20, 30")]
        public global::System.Drawing.Color Dark_Theme_Selected {
            get {
                return ((global::System.Drawing.Color)(this["Dark_Theme_Selected"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39")]
        public int selectedLocation {
            get {
                return ((int)(this["selectedLocation"]));
            }
            set {
                this["selectedLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool showNotification {
            get {
                return ((bool)(this["showNotification"]));
            }
            set {
                this["showNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3.00")]
        public decimal moviePrice {
            get {
                return ((decimal)(this["moviePrice"]));
            }
            set {
                this["moviePrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00")]
        public decimal musicPrice {
            get {
                return ((decimal)(this["musicPrice"]));
            }
            set {
                this["musicPrice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.00")]
        public decimal seriesPrice {
            get {
                return ((decimal)(this["seriesPrice"]));
            }
            set {
                this["seriesPrice"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("75, 75, 180")]
        public global::System.Drawing.Color Twilight_Theme_Preference {
            get {
                return ((global::System.Drawing.Color)(this["Twilight_Theme_Preference"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80, 110, 210")]
        public global::System.Drawing.Color Twilight_Theme_TitleBar {
            get {
                return ((global::System.Drawing.Color)(this["Twilight_Theme_TitleBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30, 80, 135")]
        public global::System.Drawing.Color Twilight_Theme_SearchBar {
            get {
                return ((global::System.Drawing.Color)(this["Twilight_Theme_SearchBar"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90, 170, 235")]
        public global::System.Drawing.Color Twilight_Theme_Selected {
            get {
                return ((global::System.Drawing.Color)(this["Twilight_Theme_Selected"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color Active_Theme_InfoPanel {
            get {
                return ((global::System.Drawing.Color)(this["Active_Theme_InfoPanel"]));
            }
            set {
                this["Active_Theme_InfoPanel"] = value;
            }
        }
    }
}
